import os
import time
import logging
import datetime
import tempfile
import subprocess
from pathlib import Path
from collections.abc import Callable
from dataclasses import dataclass

from . import ac_inf_diff
from . import song_pack_breakdown
from . import constants as CONSTANTS

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)


@dataclass
class Page:
    name: str
    filename: str
    generator: Callable
    subdirectory: str | None


def index_landing(_: bool, output_html_path: Path):
    last_update = datetime.datetime.now(tz=CONSTANTS.TIMEZONE)
    css = """
    body {
        font-family: sans-serif;
        font-size: 1.5em;
        color: #000000;
    }
    .sitelink {
        font-weight: bold;
    }
    """

    html = f"""
<html>
    <title>beatmania IIDX Infinitas English Resources</title>
    <head><style>
    {css}
    </style></head>
    <body>
        <h1>beatmania IIDX Infinitas English Resources</h1>
        <div><span>Last Updated: <b>{last_update} {CONSTANTS.TIMEZONE}</b></span></div>
        <ul>
            <li><a class="sitelink" href="iidx-infinitas-english-guide/">English Guide for How to Sign Up for IIDX Infinitas</a> - A signup guide for English speakers for <a href="https://p.eagate.573.jp/game/infinitas/2/index.html">IIDX Infinitas</a></li>
            <li><a class="sitelink" href="iidx-infinitas-customization-guide/">English Guide for How To Buy and Set IIDX Infinitas Customizations</a> - I got asked this question a couple of times, so I decided to write out the steps for setting in game customizations via the game's homepage.</li>
            <li><a class="sitelink" href="songs-in-ac-not-in-infinitas/">Songs in IIDX 34 ZINRAI Not in Infinitas</a> - List of songs that are available in the <a href="https://p.eagate.573.jp/game/2dx/34/">current arcade version of IIDX</a> that are not available in IIDX Infinitas</a></li>
            <li><a class="sitelink" href="iidx-infinitas-song-pack-value">INFINITAS Song Pack Value Breakdown</a> - The cost per song and per difficulty count for DLC song packs. Based on <a href="https://my-secret-eau-de-towel.hatenablog.com/entry/2020/08/05/090035">this Japanese post</a>, but automatically generated by scraping data off Konami's sites.</li>
        </ul>
    </body>
</html>
    """
    with open(output_html_path, "wt") as writer:
        writer.write(html)
    return True


def get_relative_page_path(relative_dir: Path, page: Path):
    if page.subdirectory is not None:
        page_dir = relative_dir / Path(page.subdirectory)
    else:
        page_dir = relative_dir
    return page_dir


def generate_page(site_dir: Path, page: Page) -> Path:
    page_dir = get_relative_page_path(site_dir, page)
    try:
        page_dir.mkdir(parents=True, exist_ok=True)
        log.info(f"Generating {page.name} html")
        page_dir_index_html = page_dir / page.filename
        page.generator(False, page_dir_index_html)
    except Exception as e:
        log.error(f"Failed to generate {page.name} html: {e}")
        raise
    return page_dir_index_html


def add_page_updates_to_git(pages_to_copy: dict[Path, Page]):
    repo_name = "everybodyeverybody.github.io"
    now = datetime.datetime.now(CONSTANTS.TIMEZONE).strftime("%Y%m%d%H%M%S")
    branch_name = f"{now}-update"
    with tempfile.TemporaryDirectory(delete=False) as temp_dir:
        repo_dir = Path(temp_dir) / Path(repo_name)
        os.chdir(temp_dir)
        subprocess.run(
            [
                "git",
                "clone",
                f"git@github.com:everybodyeverybody/{repo_name}.git",
            ],
            check=True,
        )
        os.chdir(repo_dir)
        subprocess.run(["git", "checkout", "main"], check=True)
        subprocess.run(["git", "pull"], check=True)
        subprocess.run(["git", "checkout", "-b", f"{branch_name}"], check=True)
        subprocess.run(["git", "push", "-u", "origin", f"{branch_name}"], check=True)
        for source_path, page in pages_to_copy.items():
            dest_path = get_relative_page_path(repo_dir, page) / page.filename
            print(f"cp '{source_path}' '{dest_path}'")
            _ = Path(source_path).copy(dest_path)
        subprocess.run(["git", "add", "*"], check=True)
        subprocess.run(["git", "commit", "-m", f"{now} update"], check=True)
        subprocess.run(["git", "push"], check=True)


def main():
    site_dir = CONSTANTS.DATA_DIR / Path("generate-github-pages")
    pages_to_update: list[Page] = [
        Page(
            name="ac_diff",
            subdirectory="songs-in-ac-not-in-infinitas",
            filename="index.html",
            generator=ac_inf_diff.generate,
        ),
        Page(
            name="pack value",
            subdirectory="iidx-infinitas-song-pack-value",
            filename="index.html",
            generator=song_pack_breakdown.generate,
        ),
        Page(
            name="index",
            subdirectory=None,
            filename="index.html",
            generator=index_landing,
        ),
    ]
    pages_to_copy_to_git: dict[Path, Page] = {}
    for page in pages_to_update:
        source_file = generate_page(site_dir, page)
        pages_to_copy_to_git[source_file] = page
    add_page_updates_to_git(pages_to_copy_to_git)


if __name__ == "__main__":
    main()
