#!/usr/bin/env python3
import time
import logging
import datetime
from pathlib import Path
from typing import Callable, Optional

from . import ac_inf_diff
from . import song_pack_breakdown
from . import constants as CONSTANTS

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)


def index_landing(_: bool, output_html_path: Path):
    last_update = datetime.datetime.now()
    css = """
    body {
        font-family: sans-serif;
        font-size: 1.5em;
        color: #000000;
    }
    .sitelink {
        font-weight: bold;
    }
    """

    html = f"""
<html>
    <title>beatmania IIDX Infinitas English Resources</title>
    <head><style>
    {css}
    </style></head>
    <body>
        <h1>beatmania IIDX Infinitas English Resources</h1>
        <div><span>Last Updated: {last_update} {time.tzname[1]}</span></div>
        <ul>
            <li><a class="sitelink" href="iidx-infinitas-english-guide/">English Guide for How to Sign Up for IIDX Infinitas</a> - A signup guide for English speakers for <a href="https://p.eagate.573.jp/game/infinitas/2/index.html">IIDX Infinitas</a></li>
            <li><a class="sitelink" href="songs-in-ac-not-in-infinitas/">Songs in IIDX 33 Sparkle Shower Not in Infinitas</a> - List of songs that are available in the <a href="https://p.eagate.573.jp/game/2dx/33/">current arcade version of IIDX</a> that are not available in IIDX Infinitas</a></li>
            <li><a class="sitelink" href="iidx-infinitas-song-pack-value">INFINITAS Song Pack Value Breakdown</a> - The cost per song and per difficulty count for DLC song packs. Based on <a href="https://my-secret-eau-de-towel.hatenablog.com/entry/2020/08/05/090035">this Japanese post</a>, but automatically generated by scraping data off Konami's sites.</li>
        </ul>
    </body>
</html>
    """
    with open(output_html_path, "wt") as writer:
        writer.write(html)
    return True


def generate_page(
    site_dir: Path, page_dir_name: Optional[str], generation_method: Callable
) -> bool:
    if page_dir_name is not None:
        page_dir = site_dir / Path(page_dir_name)
    else:
        page_dir = site_dir
        page_dir_name = "root"
    try:
        page_dir.mkdir(parents=True, exist_ok=True)
        log.info(f"Generating {page_dir_name} html")
        page_dir_index_html = page_dir / Path("index.html")
        generation_method(False, page_dir_index_html)
    except Exception as e:
        log.error(f"Failed to generate {page_dir_name} html: {e}")
        raise (e)
    return True


def main():
    site_dir = CONSTANTS.DATA_DIR / Path("generate-github-pages")
    generate_page(site_dir, "songs-in-ac-not-in-infinitas", ac_inf_diff.generate)
    generate_page(
        site_dir, "iidx-infinitas-song-pack-value", song_pack_breakdown.generate
    )
    generate_page(site_dir, None, index_landing)
    # TODO: implement in python
    now = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    branch_name = f"{now}-update"
    print("# Run the following: ")
    print(
        "git clone git@github.com:everybodyeverybody/everybodyeverybody.github.io.git"
    )
    print("cd everybodyeverybody.github.io")
    print("git checkout main && git pull")
    print(f"git checkout -b '{branch_name}'")
    print(f"git push -u origin '{branch_name}'")
    print(f"cp -r {site_dir}/* .")
    print("git add *")
    print(f"git commit -m '{now} update'")
    print("git push")


if __name__ == "__main__":
    main()
